# Generated by Django 5.2.13 on 2026-04-30 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_drop_rwanga_shadow_projects_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Primary', max_length=100)),
                ('room_width', models.FloatField(default=8.0)),
                ('room_height', models.FloatField(default=4.0)),
                ('furniture', models.JSONField(default=list)),
                ('cameras', models.JSONField(default=list)),
                ('paths', models.JSONField(default=list)),
                ('ai_generated', models.BooleanField(default=False)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='projects.scene')),
            ],
            options={
                'ordering': ['scene', 'name'],
            },
        ),
    ]
