# Generated by Django 5.2.13 on 2026-04-30 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_drop_rwanga_shadow_projects_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shot_number', models.CharField(max_length=20)),
                ('shot_type', models.CharField(choices=[('dialogue', 'Dialogue'), ('visual', 'Visual'), ('insert', 'Insert')], default='visual', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('lens', models.CharField(blank=True, max_length=32)),
                ('movement', models.CharField(blank=True, max_length=120)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='projects.scene')),
            ],
            options={
                'ordering': ['scene', 'order', 'shot_number'],
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup_letter', models.CharField(max_length=2)),
                ('description', models.TextField(blank=True)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='shots.shot')),
            ],
            options={
                'ordering': ['setup_letter'],
            },
        ),
        migrations.CreateModel(
            name='StoryboardFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='shots/storyboards/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboard_frames', to='shots.shot')),
            ],
            options={
                'ordering': ['shot', 'order'],
            },
        ),
    ]
