# Generated by Django 5.2.13 on 2026-04-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_drop_rwanga_shadow_projects_tables'),
        ('scheduling', '0001_initial'),
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='shots',
            field=models.ManyToManyField(blank=True, related_name='schedule_blocks', to='shots.shot'),
        ),
        migrations.AddField(
            model_name='shootday',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_days', to='projects.project'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='shoot_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduling.shootday'),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='shoot_day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_sheet', to='scheduling.shootday'),
        ),
    ]
