# Generated by Django 5.2.13 on 2026-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsession',
            name='session_type',
            field=models.CharField(choices=[('screenplay', 'Screenplay'), ('bible', 'Bible'), ('scene_selection', 'Scene Selection')], default='screenplay', max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='visibility',
            field=models.CharField(choices=[('invite_only', 'Invite Only'), ('public', 'Public')], default='invite_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionreaction',
            name='reaction_type',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree'), ('question', 'Question')], default='agree', max_length=20),
        ),
    ]
