# Generated by Django 5.2.13 on 2026-04-29 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('changed_by', models.CharField(max_length=255)),
                ('change_summary', models.TextField()),
                ('phase', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemDiagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('diagram_type', models.CharField(choices=[('architecture', 'Architecture'), ('topology', 'Topology'), ('dependency_graph', 'Dependency Graph'), ('data_model', 'Data Model'), ('flow', 'Flow')], max_length=32)),
                ('phase', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('render_format', models.CharField(choices=[('mermaid', 'Mermaid'), ('svg', 'SVG')], max_length=16)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('decision', models.TextField()),
                ('alternatives_considered', models.TextField(blank=True)),
                ('decided_by', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=16)),
                ('app_name', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='proposed', max_length=16)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='progress.designdecision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('implementation', 'Implementation'), ('design', 'Design'), ('infrastructure', 'Infrastructure'), ('documentation', 'Documentation'), ('testing', 'Testing')], max_length=32)),
                ('phase', models.CharField(max_length=16)),
                ('app_name', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=16)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('blocked_by', models.ManyToManyField(blank=True, to='progress.progresstask')),
            ],
            options={
                'ordering': ['phase', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GapBlocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gap_type', models.CharField(choices=[('design_gap', 'Design Gap'), ('spec_unclear', 'Spec Unclear'), ('dependency_missing', 'Dependency Missing'), ('technical_blocker', 'Technical Blocker'), ('question_for_owner', 'Question For Owner')], max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=16)),
                ('related_app', models.CharField(blank=True, max_length=64)),
                ('phase', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('deferred', 'Deferred')], default='open', max_length=16)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaps', to='progress.progresstask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('model_added', 'Model Added'), ('model_modified', 'Model Modified'), ('view_added', 'View Added'), ('url_added', 'URL Added'), ('test_added', 'Test Added'), ('config_changed', 'Config Changed'), ('migration_run', 'Migration Run'), ('dependency_added', 'Dependency Added')], max_length=32)),
                ('app_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('files_changed', models.JSONField(blank=True, default=list)),
                ('diff_summary', models.TextField(blank=True)),
                ('commit_hash', models.CharField(blank=True, max_length=64)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='progress.progresstask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('phase_completion', 'Phase Completion'), ('blocker', 'Blocker'), ('progress', 'Progress'), ('handoff', 'Handoff')], max_length=32)),
                ('phase', models.CharField(max_length=16)),
                ('summary', models.TextField()),
                ('gaps_found', models.ManyToManyField(blank=True, related_name='reports', to='progress.gapblocker')),
                ('tasks_blocked', models.ManyToManyField(blank=True, related_name='reports_blocked', to='progress.progresstask')),
                ('tasks_completed', models.ManyToManyField(blank=True, related_name='reports_completed', to='progress.progresstask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('update_type', models.CharField(choices=[('status_change', 'Status Change'), ('implementation', 'Implementation'), ('fix', 'Fix'), ('note', 'Note'), ('question', 'Question')], max_length=32)),
                ('body', models.TextField()),
                ('files_affected', models.JSONField(blank=True, default=list)),
                ('tests_run', models.JSONField(blank=True, default=list)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='progress.progresstask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
