# Generated by Django 5.2.13 on 2026-05-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewdecision_locked_at_reviewdecision_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdecision',
            name='lock_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='reproposed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproposals', to='reviews.reviewdecision'),
        ),
    ]
