# Generated by Django 5.2.13 on 2026-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewdecision_lock_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblereview',
            name='bible_snapshot_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
