# Generated by Django 5.2.13 on 2026-05-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_biblereview_bible_snapshot_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdecision',
            name='chain_id',
            field=models.CharField(blank=True, default='', help_text='Chain letter assignment (A, B, C, D, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='chain_name',
            field=models.CharField(blank=True, default='', help_text="Human name of the chain (e.g. 'Gesha: The Guest's Own Tragedy')", max_length=200),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='chain_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the chain (0 = first link)'),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='expression_type',
            field=models.CharField(blank=True, choices=[('emotional', 'Emotional'), ('behavioral', 'Behavioral'), ('artistic', 'Artistic'), ('memory', 'Memory'), ('broken', 'Broken')], help_text='Expression type for chain visualization', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='function_label',
            field=models.CharField(blank=True, default='', help_text="What the decision does at this point (e.g. 'stabilize uncertainty')", max_length=100),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('peak', 'Peak'), ('collapse', 'Collapse')], help_text='Intensity level for chain visualization', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='transition_label',
            field=models.CharField(blank=True, default='', help_text="How it moved from previous state (e.g. 'emotional -> behavioral')", max_length=100),
        ),
    ]
