# Generated by Django 5.2.13 on 2026-05-10 09:50

import django.db.models.deletion
import django.utils.timezone
import src.billing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_projectmembership_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('studio_unlimited', 'Studio Unlimited'), ('enterprise', 'Enterprise')], default='pro', max_length=24)),
                ('status', models.CharField(choices=[('trial', 'trial'), ('active', 'active'), ('past_due', 'past_due'), ('suspended', 'suspended'), ('cancelled', 'cancelled')], default='trial', max_length=16)),
                ('trial_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField(default=src.billing.models._trial_ends_at_default)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('payment_provider', models.CharField(blank=True, max_length=32)),
                ('payment_provider_customer_id', models.CharField(blank=True, max_length=128)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('seat_limit', models.PositiveIntegerField(default=5)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_studio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.studio')),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('meter_kind', models.CharField(choices=[('ai_requests', 'AI Requests'), ('ai_tokens', 'AI Tokens'), ('studio_seats', 'Studio Seats'), ('api_requests', 'API Requests'), ('project_count', 'Project Count'), ('production_log_size', 'Production Log Size')], max_length=32)),
                ('consumed', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=0)),
                ('overage_charged_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_meters', to='billing.subscription')),
            ],
        ),
    ]
