# Generated by Django 5.2.13 on 2026-04-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='character',
                    table='rwanga_projects_character',
                ),
                migrations.AlterModelTable(
                    name='location',
                    table='rwanga_projects_location',
                ),
                migrations.AlterModelTable(
                    name='project',
                    table='rwanga_projects_project',
                ),
                migrations.AlterModelTable(
                    name='scene',
                    table='rwanga_projects_scene',
                ),
            ],
        ),
    ]
