# Generated by GPT-5.3-Codex on 2026-04-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_character_table_alter_location_table_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS rwanga_projects_project (
                    id uuid PRIMARY KEY,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL,
                    title varchar(255) NOT NULL,
                    slug varchar(50) NOT NULL UNIQUE,
                    synopsis text NOT NULL DEFAULT '',
                    status varchar(32) NOT NULL DEFAULT 'draft',
                    studio_id uuid NOT NULL REFERENCES accounts_studio(id) ON DELETE CASCADE,
                    owner_id bigint NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS rwanga_projects_project CASCADE;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS rwanga_projects_scene (
                    id uuid PRIMARY KEY,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL,
                    number integer NOT NULL,
                    title varchar(255) NOT NULL,
                    summary text NOT NULL DEFAULT '',
                    script_text text NOT NULL DEFAULT '',
                    ordering integer NOT NULL DEFAULT 0,
                    estimated_minutes numeric(6,2) NOT NULL DEFAULT 0,
                    complexity_score integer NOT NULL DEFAULT 0,
                    draft_status varchar(20) NOT NULL DEFAULT 'draft',
                    location_type varchar(20) NOT NULL DEFAULT 'int',
                    day_night varchar(10) NOT NULL DEFAULT 'day',
                    weather varchar(20) NOT NULL DEFAULT 'clear',
                    crowd_level varchar(20) NOT NULL DEFAULT 'small',
                    vfx_complexity varchar(20) NOT NULL DEFAULT 'none',
                    language varchar(10) NOT NULL DEFAULT 'ckb',
                    last_exported_at timestamptz NULL,
                    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
                    project_id uuid NOT NULL REFERENCES rwanga_projects_project(id) ON DELETE CASCADE,
                    CONSTRAINT rwanga_projects_scene_project_number_uniq UNIQUE (project_id, number)
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS rwanga_projects_scene CASCADE;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS rwanga_projects_character (
                    id uuid PRIMARY KEY,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL,
                    name varchar(255) NOT NULL,
                    bio text NOT NULL DEFAULT '',
                    project_id uuid NOT NULL REFERENCES rwanga_projects_project(id) ON DELETE CASCADE
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS rwanga_projects_character CASCADE;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS rwanga_projects_location (
                    id uuid PRIMARY KEY,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL,
                    name varchar(255) NOT NULL,
                    description text NOT NULL DEFAULT '',
                    project_id uuid NOT NULL REFERENCES rwanga_projects_project(id) ON DELETE CASCADE
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS rwanga_projects_location CASCADE;",
        ),
    ]
