# Generated by GPT-5.3-Codex on 2026-04-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_create_rwanga_tables"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Drop only shadow tables created by old Rwanga migration shape.
                    -- Legacy ERP projects_project does not have 'slug'.
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'public' AND table_name = 'projects_project'
                    ) AND EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'projects_project'
                          AND column_name = 'slug'
                    ) THEN
                        DROP TABLE IF EXISTS projects_scene CASCADE;
                        DROP TABLE IF EXISTS projects_character CASCADE;
                        DROP TABLE IF EXISTS projects_location CASCADE;
                        DROP TABLE IF EXISTS projects_project CASCADE;
                    END IF;
                END
                $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
