# Generated by Django 5.2.13 on 2026-05-02 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_drop_rwanga_shadow_projects_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bible_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bible_finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_bibles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='bible_status',
            field=models.CharField(choices=[('empty', 'Empty'), ('draft', 'Draft'), ('in_review', 'In Review'), ('final', 'Final')], default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='bible_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='canonical_bible',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
