# Generated by Django 5.2.13 on 2026-04-29 09:39

from django.db import migrations


def ensure_missing_accounts_tables(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    # Some local databases have accounts.0001 marked as applied from an older
    # schema. Create missing tables so follow-up field migrations can run.
    for model_name in [
        "Studio",
        "ConsultantProfile",
        "ProjectConsultantAssignment",
        "ProjectMembership",
        "SignupProfile",
    ]:
        model = apps.get_model("accounts", model_name)
        if model._meta.db_table not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(model._meta.db_table)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studio_options'),
    ]

    operations = [
        migrations.RunPython(ensure_missing_accounts_tables, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='projectconsultantassignment',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='project_id',
        ),
    ]
