# Generated by Django 5.2.13 on 2026-04-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_remove_projectconsultantassignment_project_id_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconsultantassignment',
            name='project',
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='consultant_assignments',
                to='projects.project',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='memberships',
                to='projects.project',
            ),
            preserve_default=False,
        ),
    ]
