# Generated by GPT-5.3-Codex on 2026-04-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_projectconsultantassignment_project_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE accounts_user
                ADD COLUMN IF NOT EXISTS terms boolean NOT NULL DEFAULT false;
            """,
            reverse_sql="""
                ALTER TABLE accounts_user
                DROP COLUMN IF EXISTS terms;
            """,
        ),
    ]
