# Generated by GPT-5.3-Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_ensure_terms_column"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE accounts_user
                        ADD COLUMN IF NOT EXISTS is_shared_mailbox boolean NOT NULL DEFAULT false;
                    """,
                    reverse_sql="""
                        ALTER TABLE accounts_user
                        DROP COLUMN IF EXISTS is_shared_mailbox;
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="is_shared_mailbox",
                    field=models.BooleanField(default=False),
                )
            ],
        )
    ]
