# Generated by GPT-5.3-Codex on 2026-04-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_shared_mailbox"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1
                                FROM information_schema.columns
                                WHERE table_name = 'accounts_user'
                                  AND column_name = 'is_shared_mailbox'
                            ) THEN
                                UPDATE accounts_user
                                SET is_shared_mailbox = FALSE
                                WHERE is_shared_mailbox IS NULL;
                                ALTER TABLE accounts_user
                                ALTER COLUMN is_shared_mailbox SET DEFAULT FALSE;
                                ALTER TABLE accounts_user
                                ALTER COLUMN is_shared_mailbox SET NOT NULL;
                            END IF;
                        END
                        $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="user",
                    name="is_shared_mailbox",
                )
            ],
        )
    ]
