# Generated by Django 5.2.13 on 2026-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_is_shared_mailbox_state_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('director', 'دەرهێنەر'), ('production_team', 'تیمی بەرهەمهێنان'), ('reviewer', 'پێداچوونەوەکەر'), ('community', 'کۆمیونیتی'), ('full_access', 'هەموو')], default='production_team', max_length=20),
        ),
    ]
