# Generated by Django 5.2.13 on 2026-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studio_deleted_at_studio_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='snapshot_on_delete',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='specialty',
            field=models.CharField(choices=[('feature_films', 'Feature Films'), ('documentary', 'Documentary'), ('commercial', 'Commercial'), ('mixed', 'Mixed'), ('other', 'Other')], default='feature_films', max_length=32),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_api_key_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_api_key_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
