# Generated by Django 5.2.13 on 2026-05-10 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studiomembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_studios', to=settings.AUTH_USER_MODEL),
        ),
    ]
