# Generated by Django 5.2.13 on 2026-05-10 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studio_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='magic_link_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='recovery_grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed_with_project', 'completed_with_project'), ('removed', 'removed')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='tier',
            field=models.CharField(choices=[('production', 'production'), ('community', 'community')], default='production', max_length=16),
        ),
    ]
