# Generated by Django 5.2.13 on 2026-04-30 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_drop_rwanga_shadow_projects_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='scripts/files/')),
                ('script_format', models.CharField(default='plain', max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element_type', models.CharField(choices=[('action', 'Action'), ('dialogue', 'Dialogue'), ('heading', 'Heading'), ('character', 'Character'), ('transition', 'Transition'), ('parenthetical', 'Parenthetical')], max_length=32)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_elements', to='projects.character')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_elements', to='projects.scene')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='scripts.script')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
