# Generated by Django 5.2.13 on 2026-04-30 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='scripts.script')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
