# Generated by Django 5.2.13 on 2026-05-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='int_ext',
            field=models.CharField(choices=[('INT', 'INT'), ('EXT', 'EXT')], default='INT', max_length=8),
        ),
        migrations.AddField(
            model_name='location',
            name='time_of_day',
            field=models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT'), ('DAWN', 'DAWN'), ('DUSK', 'DUSK')], default='DAY', max_length=8),
        ),
    ]
