# Generated by Django 5.2.13 on 2026-05-10 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_json', models.JSONField()),
                ('actor_type', models.CharField(default='system', max_length=32)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=128)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_versio_content_433098_idx')],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
