# Generated by Django 5.2.13 on 2026-05-10 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studio_deleted_at_studio_deleted_by_and_more'),
        ('core', '0001_initial'),
        ('projects', '0005_project_bible_finalized_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('user', 'user'), ('ai_agent', 'ai_agent'), ('system', 'system'), ('external_mcp', 'external_mcp')], default='system', max_length=32)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('training_only', 'training_only')], default='private', max_length=16)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.studio')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['studio', 'timestamp'], name='core_produc_studio__29050b_idx'), models.Index(fields=['project', 'timestamp'], name='core_produc_project_1ead66_idx'), models.Index(fields=['actor_type', 'timestamp'], name='core_produc_actor_t_d4e919_idx')],
            },
        ),
    ]
