# Generated by Django 5.2.13 on 2026-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='actor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
