# Generated by Django 5.2.13 on 2026-04-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('projects', '0004_drop_rwanga_shadow_projects_tables'),
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingnote',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_notes', to='shots.shot'),
        ),
        migrations.AddField(
            model_name='prop',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='projects.project'),
        ),
        migrations.AddField(
            model_name='prop',
            name='scenes',
            field=models.ManyToManyField(blank=True, related_name='props', to='projects.scene'),
        ),
        migrations.AddField(
            model_name='soundnote',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_notes', to='shots.shot'),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to='projects.character'),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to='projects.scene'),
        ),
    ]
